export const DB_CONFIG = {
  HOST: process.env.DB_HOST,
  PORT: process.env.DB_PORT,
  DB_NAME: process.env.DB_NAME,
  USER: process.env.DB_USER,
  PASSWORD: process.env.DB_PASSWORD,
};
export const SERVER_CONFIG = {
  HOST: process.env.SERVER_HOST || "0.0.0.0",
  PORT: Number(process.env.SERVER_PORT || 3000),
  ENV: process.env.NODE_ENV || process.env.SERVER_ENV || "development",
  RESPONSE_ERROR_STACK: process.env.RESPONSE_ERROR_STACK === "true",
  ACCESS_TOKEN_USER_SECRET: process.env.SERVER_ACCESS_TOKEN_USER_SECRET,
  ACCESS_TOKEN_ADMIN_SECRET: process.env.SERVER_ACCESS_TOKEN_ADMIN_SECRET,
  REFRESH_TOKEN_USER_SECRET: process.env.SERVER_REFRESH_TOKEN_USER_SECRET,
  REFRESH_TOKEN_ADMIN_SECRET: process.env.SERVER_REFRESH_TOKEN_ADMIN_SECRET,
  ACCESS_TOKEN_USER_EXPIRY: process.env.SERVER_ACCESS_TOKEN_USER_EXPIRY,
  ACCESS_TOKEN_ADMIN_EXPIRY: process.env.SERVER_ACCESS_TOKEN_ADMIN_EXPIRY,
  REFRESH_TOKEN_USER_EXPIRY: process.env.SERVER_REFRESH_TOKEN_USER_EXPIRY,
  REFRESH_TOKEN_ADMIN_EXPIRY: process.env.SERVER_REFRESH_TOKEN_ADMIN_EXPIRY,
};
